using Content.Shared.Body.Part;
using Content.Shared.Body.Systems;
using Content.Shared.ScavPrototype.NewMedical.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Content.Shared.ScavPrototype.NewMedical.Woundable.Components;

namespace Content.Client.ScavPrototype.NewMedical.UserInterface.PartStatus.Widgets;

[GenerateTypedNameReferences]
public sealed partial class PartStatusControl : UIWidget
{
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly Dictionary<string, TextureRect> _partStatusControls;
    private readonly PartStatusUIController _controller;
    public event Action<GUIBoundKeyEventArgs>? OnMouseDown;
    public PartStatusControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<PartStatusUIController>();
        _partStatusControls = new Dictionary<string, TextureRect>
        {
            { "head", DollHead },
            { "chest", DollTorso },
            { "groin", DollGroin },
            { "leftarm", DollLeftArm },
            { "lefthand", DollLeftHand },
            { "rightarm", DollRightArm },
            { "righthand", DollRightHand },
            { "leftleg", DollLeftLeg },
            { "leftfoot", DollLeftFoot },
            { "rightleg", DollRightLeg },
            { "rightfoot", DollRightFoot },
        };
        MouseFilter = MouseFilterMode.Stop;
        //OnKeyBindDown += OnClicked;
    }

    public void SetTextures(List<(BodyPartType type, BodyPartSymmetry symmetry, float integrity)> partsWoundable)
    {
        foreach (var (type, symmetry, integrity) in partsWoundable)
        {
            string enumName = GetBodyPartName(type, symmetry);
            int enumValue = (int) (Math.Abs(integrity-1)*6);
            var texture = new SpriteSpecifier.Rsi(new ResPath($"/Textures/_ScavPrototype/Interface/PartsStatus/{enumName}.rsi"), $"{enumName}_{enumValue}");
            _partStatusControls[enumName].Texture = _controller.GetTexture(texture);
        }
    }

    /*private void OnClicked(GUIBoundKeyEventArgs args)
    {
        if (_timing.IsFirstTimePredicted && args.Function == EngineKeyFunctions.Use)
            _controller.GetPartStatusMessage();
    }*/

    public void SetVisible(bool visible) => this.Visible = visible;

    public string GetBodyPartName(BodyPartType type, BodyPartSymmetry symmetry)
    {
        return (type, symmetry) switch
        {
            (BodyPartType.Head, _) => "head",
            (BodyPartType.Torso, _) => "chest",
            (BodyPartType.Groin, _) => "groin",
            (BodyPartType.Arm, BodyPartSymmetry.Left) => "leftarm",
            (BodyPartType.Arm, BodyPartSymmetry.Right) => "rightarm",
            (BodyPartType.Hand, BodyPartSymmetry.Left) => "lefthand",
            (BodyPartType.Hand, BodyPartSymmetry.Right) => "righthand",
            (BodyPartType.Leg, BodyPartSymmetry.Left) => "leftleg",
            (BodyPartType.Leg, BodyPartSymmetry.Right) => "rightleg",
            (BodyPartType.Foot, BodyPartSymmetry.Left) => "leftfoot",
            (BodyPartType.Foot, BodyPartSymmetry.Right) => "rightfoot",
            _ => "Unknown",
        };
    }
}
