using Content.Shared.Body.Part;
using Content.Shared.Body.Systems;
using Content.Shared.ScavPrototype.NewMedical.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using Robust.Shared.Timing;

namespace Content.Client.ScavPrototype.NewMedical.UserInterface.PartStatus.Widgets;

[GenerateTypedNameReferences]
public sealed partial class PartStatusControl : UIWidget
{
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly Dictionary<TargetBodyPart, TextureRect> _partStatusControls;
    private readonly PartStatusUIController _controller;
    public event Action<GUIBoundKeyEventArgs>? OnMouseDown;
    public PartStatusControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<PartStatusUIController>();
        _partStatusControls = new Dictionary<TargetBodyPart, TextureRect>
        {
            { TargetBodyPart.Head, DollHead },
            { TargetBodyPart.Torso, DollTorso },
            { TargetBodyPart.Groin, DollGroin },
            { TargetBodyPart.LeftArm, DollLeftArm },
            { TargetBodyPart.LeftHand, DollLeftHand },
            { TargetBodyPart.RightArm, DollRightArm },
            { TargetBodyPart.RightHand, DollRightHand },
            { TargetBodyPart.LeftLeg, DollLeftLeg },
            { TargetBodyPart.LeftFoot, DollLeftFoot },
            { TargetBodyPart.RightLeg, DollRightLeg },
            { TargetBodyPart.RightFoot, DollRightFoot },
        };
        MouseFilter = MouseFilterMode.Stop;
        //OnKeyBindDown += OnClicked;
    }

    public void SetTextures(IEnumerable<(TargetBodyPart targetPart, BodyPartComponent Component)> parts)
    {
        foreach (var (targetPart, bodyPart) in parts)
        {
            string enumName = Enum.GetName(typeof(TargetBodyPart), targetPart) ?? "Unknown";
            int enumValue = (int) (Math.Abs(bodyPart.Integrity-1)*6);
            var texture = new SpriteSpecifier.Rsi(new ResPath($"/Textures/_ScavPrototype/Interface/PartsStatus/{enumName.ToLowerInvariant()}.rsi"), $"{enumName.ToLowerInvariant()}_{enumValue}");
            _partStatusControls[targetPart].Texture = _controller.GetTexture(texture);
        }
    }

    /*private void OnClicked(GUIBoundKeyEventArgs args)
    {
        if (_timing.IsFirstTimePredicted && args.Function == EngineKeyFunctions.Use)
            _controller.GetPartStatusMessage();
    }*/

    public void SetVisible(bool visible) => this.Visible = visible;

}
